- name: packages | Update apt cache
  apt: update_cache=yes
  sudo: yes

- name: packages | Install must-have packages - {{ item }}
  apt: pkg= {{ item }}
  with_items: FirstFive_packages
  sudo: yes

- name: packages | Install must-have packages for workstation machines - {{ item }}
  apt: pkg= {{ item }}
  with_items: FirstFive_workstation_packages
  when: FirstFive_machine == "workstation"
